yamlname: Deploy to Azure AKS

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  RESOURCE_GROUP: nexus-or-planner-rg
  LOCATION: westeurope
  ACR_NAME: nexusorplanneracr
  AKS_NAME: nexus-or-planner-aks
  IMAGE_NAME: nexus-or-planner

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Resource Group
      run: |
        az group create --name ${{ env.RESOURCE_GROUP }} --location ${{ env.LOCATION }}

    - name: Create Azure Container Registry
      run: |
        az acr create \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --name ${{ env.ACR_NAME }} \
          --sku Basic \
          --admin-enabled true || echo "ACR might already exist"

    - name: Build and push image
      run: |
        az acr build \
          --registry ${{ env.ACR_NAME }} \
          --image ${{ env.IMAGE_NAME }}:${{ github.sha }} \
          --image ${{ env.IMAGE_NAME }}:latest \
          .

    - name: Create AKS cluster
      run: |
        az aks create \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --name ${{ env.AKS_NAME }} \
          --node-count 2 \
          --node-vm-size Standard_B2s \
          --enable-addons monitoring \
          --generate-ssh-keys \
          --attach-acr ${{ env.ACR_NAME }} || echo "AKS might already exist"

    - name: Get AKS credentials
      run: |
        az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.AKS_NAME }} --overwrite-existing

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Install NGINX Ingress
      run: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update
        helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
          --create-namespace \
          --namespace ingress-nginx \
          --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path"=/healthz

    - name: Wait for ingress controller
      run: |
        kubectl wait --namespace ingress-nginx \
          --for=condition=ready pod \
          --selector=app.kubernetes.io/component=controller \
          --timeout=300s

    - name: Create namespace and secrets
      run: |
        kubectl create namespace nexus-or-planner --dry-run=client -o yaml | kubectl apply -f -
        kubectl create secret generic nexus-or-planner-secrets \
          --from-literal=GOOGLE_API_KEY="${{ secrets.GOOGLE_API_KEY }}" \
          --namespace=nexus-or-planner \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy application
      run: |
        # Update the image in the manifest
        sed "s|<ACR_NAME>|${{ env.ACR_NAME }}|g" kubernetes-manifests.yaml > k8s-deploy.yaml
        sed -i "s|:latest|:${{ github.sha }}|g" k8s-deploy.yaml
        
        # Apply the manifest
        kubectl apply -f k8s-deploy.yaml
        
        # Wait for deployment
        kubectl wait --for=condition=available --timeout=600s deployment/nexus-or-planner -n nexus-or-planner

    - name: Get application URL
      run: |
        echo "Waiting for external IP..."
        sleep 60
        EXTERNAL_IP=""
        for i in {1..10}; do
          EXTERNAL_IP=$(kubectl get svc --namespace ingress-nginx ingress-nginx-controller --template="{{range .status.loadBalancer.ingress}}{{.ip}}{{end}}" 2>/dev/null || echo "")
          if [ -n "$EXTERNAL_IP" ]; then
            break
          fi
          echo "Attempt $i: Waiting for external IP..."
          sleep 30
        done
        
        if [ -n "$EXTERNAL_IP" ]; then
          echo "🎉 Application is available at: http://$EXTERNAL_IP"
          echo "APPLICATION_URL=http://$EXTERNAL_IP" >> $GITHUB_ENV
        else
          echo "⚠️ External IP not ready yet. Check later with:"
          echo "kubectl get svc --namespace ingress-nginx ingress-nginx-controller"
        fi
